[project]
name = "coc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "depth-anything-v2",
    "langchain>=0.3.20",
    "sam-2",
    "torch>=2.5.1",
    "trellis",
]


[tool.uv.sources]
torch = [
    { index = "pytorch-cu" },
]
torchvision = [
    { index = "pytorch-cu" },
]
sam-2 = { path = "submodules/sam2" }
depth-anything-v2 = { workspace = true }
trellis = { workspace = true }

[[tool.uv.index]]
name = "pytorch-cu"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.workspace]
members = ["submodules/TRELLIS", "submodules/Depth-Anything-V2"]

[tool.uv]
index-url = "https://mirrors.bfsu.edu.cn/pypi/web/simple"
